import React, { useEffect, useState } from 'react';
import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import Navbar from '../components/Navbar';
import { getCategoryReport } from '../services/reportService';

const COLORS = ['var(--primary-color)', 'var(--accent-color)', '#0ea5e9', '#14b8a6', 'var(--success-color)', 'var(--warning-color)', '#8b5cf6', 'var(--danger-color)'];

function CategoryReportPage() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    getCategoryReport()
      .then(res => setData(res.data))
      .catch(() => setError('Failed to load category data.'))
      .finally(() => setLoading(false));
  }, []);

  const chartData = data.map(item => ({
    name: item.categoryDescription,
    value: item.totalAmount,
  }));

  return (
    <>
      <Navbar />
      <div className="page-container">
        <div className="page-header">
          <div>
            <h1 className="page-title">Fine Category Breakdown</h1>
            <p className="page-subtitle">Analysis of revenue generated by different violation types.</p>
          </div>
        </div>

        {loading && <p>Loading...</p>}
        {error && <div className="login-error">{error}</div>}

        {data.length > 0 && (
          <div style={{ display: 'flex', gap: '28px', flexWrap: 'wrap', alignItems: 'flex-start' }}>
            
            <div className="card" style={{ flex: '1 1 350px', minWidth: '300px' }}>
              <h2 className="card-title">Revenue by Category</h2>
              <div style={{ height: '340px', width: '100%' }}>
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie 
                      data={chartData} 
                      dataKey="value" 
                      nameKey="name" 
                      cx="50%" 
                      cy="50%" 
                      outerRadius={110} 
                      innerRadius={70}
                      paddingAngle={2}
                      labelLine={false}
                    >
                      {chartData.map((_, i) => (
                        <Cell key={i} fill={COLORS[i % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip formatter={val => `Rs. ${val.toLocaleString()}`} />
                    <Legend verticalAlign="bottom" height={36}/>
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="table-container" style={{ flex: '1.5 1 450px', minWidth: '350px' }}>
              <table>
                <thead>
                  <tr>
                    <th>Category</th>
                    <th>Code</th>
                    <th>Fines Paid</th>
                    <th>Total (Rs.)</th>
                  </tr>
                </thead>
                <tbody>
                  {data.map((row, i) => (
                    <tr key={i}>
                      <td style={{ fontWeight: 500 }}>{row.categoryDescription}</td>
                      <td style={{ color: 'var(--text-muted)' }}>{row.categoryCode}</td>
                      <td>{row.totalFines}</td>
                      <td style={{ fontWeight: 600 }}>Rs. {row.totalAmount?.toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

          </div>
        )}
      </div>
    </>
  );
}

export default CategoryReportPage;