spring.application.name=Backend

#initialization
# Copy this file, rename to application.properties
# and fill your own Supabase credentials

spring.datasource.url=postgresql://postgres:Akdpraneeth123$@db.dejaomcdgfnqnkhucjfi.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Akdpraneeth123$
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080